name: meow

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print release
        run: lsb_release -a

      - name: copy /var/lib/apt/lists
        run: sudo cp -r /var/lib/apt/lists var-lib-apt-lists && sudo chmod 777 -R var-lib-apt-lists

      - name: get installed packages
        run: bash -c "dpkg-query -f '\${binary:Package}\n' -W > packages.txt"

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages.txt
          if-no-files-found: error

      - name: "dump all packages"
        run: |
          mkdir packages
          cd packages
          for package in $(dpkg-query -f '${binary:Package}\n' -W); do
            apt-get download "$package"
          done
          cd ..

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages
          if-no-files-found: error
