name: meow

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print release
        run: lsb_release -a

      - name: get installed packages
        run: bash -c "dpkg-query -f '\${binary:Package}\n' -W > packages.txt"

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages.txt
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: apt-conf
          path: /etc/apt
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: var-lib-apt-lists
          path: /var/lib/apt/lists/
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: keyrings
          path: /usr/share/keyrings
          if-no-files-found: error
